# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e623d065b6649107df4a15899cd60656f23744d389713d3cc0c587104af7740b07ca2335c3a681cee29ca7e3821103382ef7ab7a6493bd912c859571b8df1d4a

test:
  secret_key_base: eb614cacdbe3a3e0eef6723346d641b7412b3f25a8abe8ebeaadddfbf3fd33f6243745b1b538361c2b9723a8bbe714046b1c0793f966457a4aabd95e26fd1b80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
